function createMainGUI(originalImage, grayImage, reconstructedImage, ...
    imageInfo, analysis, metrics, isLossless, imagePath)
% Main frontend GUI.

mainFig = figure( ...
    'Name', 'Huffman Image Compression - Optimized', ...
    'NumberTitle', 'off', ...
    'Color', [0.94 0.94 0.94], ...
    'Position', [70 50 1300 820]);

uicontrol('Style','text','Parent',mainFig,'Units','normalized', ...
    'Position',[0.15 0.945 0.70 0.045], ...
    'String','HUFFMAN IMAGE COMPRESSION', ...
    'FontSize',20,'FontWeight','bold', ...
    'ForegroundColor',[0.05 0.20 0.45], ...
    'BackgroundColor',[0.94 0.94 0.94]);

uicontrol('Style','text','Parent',mainFig,'Units','normalized', ...
    'Position',[0.15 0.915 0.70 0.03], ...
    'String','Digital Communication | Lossless Source Coding | Backend Algorithm Exposed', ...
    'FontSize',11,'ForegroundColor',[0.25 0.25 0.25], ...
    'BackgroundColor',[0.94 0.94 0.94]);

ax1 = axes('Parent',mainFig,'Units','normalized','Position',[0.05 0.48 0.38 0.38]);
imshow(grayImage,'Parent',ax1);
title(ax1,sprintf('ORIGINAL GRAYSCALE IMAGE\n%.2f KB raw data',metrics.originalSizeKB), ...
    'FontSize',13,'FontWeight','bold');

ax2 = axes('Parent',mainFig,'Units','normalized','Position',[0.57 0.48 0.38 0.38]);
imshow(reconstructedImage,'Parent',ax2);
title(ax2,sprintf('RECONSTRUCTED IMAGE\nLossless: %s', ...
    ternaryLossless(isLossless)),'FontSize',13,'FontWeight','bold');

panel = uipanel('Parent',mainFig,'Units','normalized', ...
    'Position',[0.04 0.235 0.92 0.19], ...
    'Title','Compression Performance','FontSize',12,'FontWeight','bold', ...
    'BackgroundColor',[0.88 0.90 0.94]);

items = { ...
    sprintf('Original\n%.2f KB',metrics.originalSizeKB), ...
    sprintf('Encoded Data\n%.2f KB',metrics.encodedDataSizeKB), ...
    sprintf('Ratio\n%.3f : 1',metrics.compressionRatio), ...
    sprintf('Efficiency\n%.2f %%',metrics.codingEfficiency), ...
    sprintf('Entropy\n%.4f bpp',metrics.entropy), ...
    sprintf('Avg Code Length\n%.4f bpp',metrics.averageCodeLength)};

for k=1:numel(items)
    x = 0.015 + (k-1)*0.163;
    uicontrol('Style','text','Parent',panel,'Units','normalized', ...
        'Position',[x 0.30 0.15 0.55], ...
        'String',items{k},'FontSize',10,'FontWeight','bold', ...
        'BackgroundColor',[0.88 0.90 0.94]);
end

% Buttons
labels = {'Project Info','Image Info','Detailed Results', ...
    'Compression Graph','Huffman Calculation','Huffman Tree', ...
    'Encoded Stream','Exit'};

callbacks = { ...
    @(~,~) showProjectInfo(), ...
    @(~,~) showImageInformation(imageInfo), ...
    @(~,~) showDetailedResults(metrics,analysis,isLossless), ...
    @(~,~) showCompressionGraph(metrics), ...
    @(~,~) showHuffmanCalculation(analysis), ...
    @(~,~) showHuffmanTree(analysis.tree), ...
    @(~,~) showEncodedStream(analysis), ...
    @(~,~) close(mainFig)};

for k=1:numel(labels)
    x = 0.035 + (k-1)*0.117;
    uicontrol('Style','pushbutton','Parent',mainFig,'Units','normalized', ...
        'Position',[x 0.15 0.105 0.055], ...
        'String',labels{k},'FontSize',9,'FontWeight','bold', ...
        'Callback',callbacks{k});
end

uicontrol('Style','text','Parent',mainFig,'Units','normalized', ...
    'Position',[0.05 0.07 0.90 0.05], ...
    'String',sprintf('Input: %s | Encoded bits: %d | Estimated tree overhead: %d bits', ...
        imagePath,analysis.encodedBitCount,metrics.estimatedTreeOverheadBits), ...
    'FontSize',9,'ForegroundColor',[0.2 0.2 0.2], ...
    'BackgroundColor',[0.94 0.94 0.94]);

end

function out = ternaryLossless(v)
if v, out='YES'; else, out='NO'; end
end
