function showProjectInfo()
text = sprintf([ ...
    'IMAGE COMPRESSION USING HUFFMAN CODING\n\n' ...
    'Technique: Huffman source coding\n' ...
    'Compression type: Lossless\n\n' ...
    'BACKEND CALCULATION:\n' ...
    '1. Read image and convert to grayscale\n' ...
    '2. Count pixel frequencies\n' ...
    '3. Convert frequency to probability\n' ...
    '4. Calculate source entropy\n' ...
    '5. Build Huffman tree\n' ...
    '6. Repeatedly merge the two least-probable nodes\n' ...
    '7. Assign 0 to the left branch and 1 to the right branch\n' ...
    '8. Generate variable-length codes\n' ...
    '9. Encode every pixel\n' ...
    '10. Decode the bitstream\n' ...
    '11. Verify lossless reconstruction\n\n' ...
    'Unlike the original version, the main Huffman tree calculation\n' ...
    'is implemented explicitly in the backend.']);
msgbox(text,'Project Information','help');
end
