function showImageInformation(info)
text = sprintf([ ...
    'IMAGE INFORMATION\n\n' ...
    'File Name:\n%s\n\n' ...
    'Original Type:\n%s\n\n' ...
    'Original Resolution:\n%d x %d pixels\n\n' ...
    'Processing Resolution:\n%d x %d pixels\n\n' ...
    'Total Pixels:\n%d\n\n' ...
    'Unique Intensity Levels:\n%d\n\n' ...
    'Processing:\n%s'], ...
    info.fileName,info.imageType,info.originalRows,info.originalCols, ...
    info.grayRows,info.grayCols,info.totalPixels, ...
    info.numberOfIntensityLevels,info.processingType);
msgbox(text,'Image Information','help');
end
