function showDetailedResults(metrics,analysis,isLossless)
verification = 'FAIL';
if isLossless
    verification = 'PASS - Lossless Reconstruction';
end

text = sprintf([ ...
    'HUFFMAN COMPRESSION RESULTS\n\n' ...
    'Original raw data: %.2f KB\n' ...
    'Encoded bitstream: %.2f KB\n' ...
    'Saved space (encoded stream): %.2f KB\n' ...
    'Compression ratio: %.3f : 1\n' ...
    'Compression percentage: %.3f %%\n\n' ...
    'Entropy: %.6f bits/pixel\n' ...
    'Average Huffman code length: %.6f bits/pixel\n' ...
    'Coding efficiency: %.3f %%\n' ...
    'Average encoded bits/pixel: %.6f\n\n' ...
    'Estimated tree overhead: %d bits\n' ...
    'Estimated total compressed size: %.2f KB\n' ...
    'Estimated realistic ratio: %.3f : 1\n\n' ...
    'Encoding time: %.6f s\n' ...
    'Decoding time: %.6f s\n' ...
    'Encoded bits: %d\n' ...
    'Unique symbols: %d\n\n' ...
    'Verification: %s'], ...
    metrics.originalSizeKB,metrics.encodedDataSizeKB,metrics.savedSpaceKB, ...
    metrics.compressionRatio,metrics.compressionPercentage, ...
    metrics.entropy,metrics.averageCodeLength,metrics.codingEfficiency, ...
    metrics.averageBitsPerPixel,metrics.estimatedTreeOverheadBits, ...
    metrics.estimatedTotalCompressedSizeKB,metrics.realisticCompressionRatio, ...
    analysis.encodingTime,analysis.decodingTime,analysis.encodedBitCount, ...
    numel(analysis.uniqueSymbols),verification);

msgbox(text,'Detailed Results','help');
end
