function showHuffmanCalculation(analysis)
% Display the calculations behind Huffman coding.

fig = figure('Name','Huffman Backend Calculation','NumberTitle','off', ...
    'Color',[0.95 0.95 0.95],'Position',[80 60 1250 760]);

uicontrol('Style','text','Parent',fig,'Units','normalized', ...
    'Position',[0.10 0.945 0.80 0.045], ...
    'String','HUFFMAN BACKEND CALCULATION', ...
    'FontSize',18,'FontWeight','bold', ...
    'BackgroundColor',[0.95 0.95 0.95]);

% Histogram/probability table
n = numel(analysis.uniqueSymbols);
tableData = cell(n,7);

for k=1:n
    tableData{k,1} = analysis.uniqueSymbols(k);
    tableData{k,2} = analysis.counts(k);
    tableData{k,3} = analysis.probabilities(k);
    tableData{k,4} = analysis.codeStrings{k};
    tableData{k,5} = analysis.codeLengths(k);
    tableData{k,6} = analysis.probabilities(k)*analysis.codeLengths(k);
    tableData{k,7} = analysis.probabilities(k)*log2(1/analysis.probabilities(k));
end

uitable('Parent',fig,'Units','normalized','Position',[0.04 0.35 0.92 0.53], ...
    'Data',tableData, ...
    'ColumnName',{'Pixel','Frequency','Probability','Huffman Code', ...
                  'Code Length','P x L','P x log2(1/P)'}, ...
    'ColumnWidth',{70,90,110,260,90,100,130},'FontSize',9);

summary = sprintf([ ...
    'FORMULAS AND FINAL CALCULATIONS\n\n' ...
    'Probability: P(i) = Frequency(i) / Total Pixels\n' ...
    'Entropy: H = -sum(P(i) log2(P(i))) = %.6f bits/pixel\n' ...
    'Average Code Length: L = sum(P(i) x CodeLength(i)) = %.6f bits/pixel\n' ...
    'Coding Efficiency = H/L x 100 = %.3f %%\n' ...
    'Encoded stream = %d bits\n' ...
    'Compression ratio = %.3f : 1'], ...
    analysis.entropy,analysis.averageCodeLength, ...
    100*analysis.entropy/analysis.averageCodeLength, ...
    analysis.encodedBitCount, ...
    analysis.totalPixels*8/analysis.encodedBitCount);

uicontrol('Style','edit','Parent',fig,'Units','normalized', ...
    'Position',[0.04 0.08 0.92 0.21], ...
    'String',summary,'Max',10,'Min',0,'Enable','inactive', ...
    'HorizontalAlignment','left','FontSize',11, ...
    'BackgroundColor','white');
end
