function showEncodedStream(analysis)
% Show a readable portion of the generated binary stream.

bits = char(analysis.encodedData + '0');
maxDisplay = min(numel(bits), 5000);

if numel(bits) > maxDisplay
    displayText = [bits(1:maxDisplay) ...
        sprintf('\n\n... showing first %d of %d bits ...', ...
        maxDisplay,numel(bits))];
else
    displayText = bits;
end

fig = figure('Name','Huffman Encoded Bitstream','NumberTitle','off', ...
    'Color','white','Position',[150 120 1100 650]);

uicontrol('Style','text','Parent',fig,'Units','normalized', ...
    'Position',[0.05 0.91 0.90 0.06], ...
    'String',sprintf('ENCODED BITSTREAM (%d bits)',analysis.encodedBitCount), ...
    'FontSize',16,'FontWeight','bold','BackgroundColor','white');

uicontrol('Style','edit','Parent',fig,'Units','normalized', ...
    'Position',[0.05 0.12 0.90 0.72], ...
    'String',displayText,'Max',20,'Min',0,'Enable','inactive', ...
    'HorizontalAlignment','left','FontName','Courier New', ...
    'FontSize',9,'BackgroundColor','white');

uicontrol('Style','text','Parent',fig,'Units','normalized', ...
    'Position',[0.05 0.04 0.90 0.05], ...
    'String','Each pixel is replaced by its variable-length Huffman code.', ...
    'FontSize',10,'BackgroundColor','white');
end
